version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: "20:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
