name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - ruby-4.0
          - ruby-3.4
          - ruby-3.3
          - ruby-3.2
          - ruby-3.1
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby-version}}
      - name: Install dependencies
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y curl libarchive-tools
          bundle
      - name: Output versions
        run: |
          set -eux
          git --version
          bsdtar --version
          curl --version
          ruby --version
          gem --version
          bundle --version
          bundle list
      - name: Test
        run: |
          set -eux
          current_version="$(ruby -r./lib/pandoc_binary/version -e 'puts(PandocBinary::VERSION)')"
          ./bin/test "$current_version"
